### ISSUE TITLE
Output typo replication_group_coniguration_endpoint_address

### ISSUE THREAD

**Issue by fmidaglia-gocloud** [terraform-aws-modules/terraform-aws-elasticache#17]
## Description

There is a writing error in one of the outputs:
- `replication_group_coniguration_endpoint_address` => `replication_group_configuration_endpoint_address`

## Versions

- Module version [Required]: v1.2.3

**Comment by syedimranhassan** [comment]
@fmidaglia-gocloud I have fixed the above issue in [this](https://github.com/terraform-aws-modules/terraform-aws-elasticache/pull/18) PR.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.2.4 :tada:
